project_id = "grliixgrwhzwgmarvmhi"

[api]
port = 54331

[db]
port = 54332
shadow_port = 54330

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = []
enable_anonymous_sign_ins = true

[auth.email]
enable_confirmations = true
max_frequency = "1m"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[functions.send-friend-notification]
verify_jwt = true

[functions.broadcast-app-update]
verify_jwt = false
