import Foundation

struct UniversityOption: Identifiable, Hashable, Sendable {
    let id: String
    let name: String
    let state: String?
    let stateCode: String?
    let country: String

    var location: String {
        [state, country].compactMap { $0 }.filter { !$0.isEmpty }.joined(separator: ", ")
    }

    func matches(_ query: String) -> Bool {
        let searchable = [name, state, stateCode, country]
            .compactMap { $0 }
            .joined(separator: " ")
        return searchable.localizedCaseInsensitiveContains(query)
    }
}

enum UniversityCatalog {
    static let none = UniversityOption(
        id: "non-school",
        name: "No university",
        state: nil,
        stateCode: nil,
        country: ""
    )

    static let universities: [UniversityOption] = ([
        // United States
        us("air-force", "United States Air Force Academy", "Colorado", "CO"),
        us("alabama", "University of Alabama", "Alabama", "AL"),
        us("alaska", "University of Alaska Fairbanks", "Alaska", "AK"),
        us("arizona-state", "Arizona State University", "Arizona", "AZ"),
        us("arkansas", "University of Arkansas", "Arkansas", "AR"),
        us("auburn", "Auburn University", "Alabama", "AL"),
        us("baylor", "Baylor University", "Texas", "TX"),
        us("boise-state", "Boise State University", "Idaho", "ID"),
        us("boston-college", "Boston College", "Massachusetts", "MA"),
        us("boston-university", "Boston University", "Massachusetts", "MA"),
        us("brown", "Brown University", "Rhode Island", "RI"),
        us("byu", "Brigham Young University", "Utah", "UT"),
        us("caltech", "California Institute of Technology", "California", "CA"),
        us("carnegie-mellon", "Carnegie Mellon University", "Pennsylvania", "PA"),
        us("case-western", "Case Western Reserve University", "Ohio", "OH"),
        us("clemson", "Clemson University", "South Carolina", "SC"),
        us("columbia", "Columbia University", "New York", "NY"),
        us("connecticut", "University of Connecticut", "Connecticut", "CT"),
        us("cornell", "Cornell University", "New York", "NY"),
        us("dartmouth", "Dartmouth College", "New Hampshire", "NH"),
        us("delaware", "University of Delaware", "Delaware", "DE"),
        us("duke", "Duke University", "North Carolina", "NC"),
        us("emory", "Emory University", "Georgia", "GA"),
        us("florida", "University of Florida", "Florida", "FL"),
        us("florida-state", "Florida State University", "Florida", "FL"),
        us("george-washington", "George Washington University", "District of Columbia", "DC"),
        us("georgetown", "Georgetown University", "District of Columbia", "DC"),
        us("georgia", "University of Georgia", "Georgia", "GA"),
        us("georgia-tech", "Georgia Institute of Technology", "Georgia", "GA"),
        us("harvard", "Harvard University", "Massachusetts", "MA"),
        us("hawaii", "University of Hawaiʻi at Mānoa", "Hawaii", "HI"),
        us("houston", "University of Houston", "Texas", "TX"),
        us("howard", "Howard University", "District of Columbia", "DC"),
        us("idaho", "University of Idaho", "Idaho", "ID"),
        us("indiana", "Indiana University Bloomington", "Indiana", "IN"),
        us("iowa", "University of Iowa", "Iowa", "IA"),
        us("iowa-state", "Iowa State University", "Iowa", "IA"),
        us("johns-hopkins", "Johns Hopkins University", "Maryland", "MD"),
        us("kansas", "University of Kansas", "Kansas", "KS"),
        us("kansas-state", "Kansas State University", "Kansas", "KS"),
        us("kentucky", "University of Kentucky", "Kentucky", "KY"),
        us("lsu", "Louisiana State University", "Louisiana", "LA"),
        us("maine", "University of Maine", "Maine", "ME"),
        us("maryland", "University of Maryland, College Park", "Maryland", "MD"),
        us("miami", "University of Miami", "Florida", "FL"),
        us("michigan-state", "Michigan State University", "Michigan", "MI"),
        us("minnesota", "University of Minnesota Twin Cities", "Minnesota", "MN"),
        us("mississippi", "University of Mississippi", "Mississippi", "MS"),
        us("mississippi-state", "Mississippi State University", "Mississippi", "MS"),
        us("missouri", "University of Missouri", "Missouri", "MO"),
        us("mit", "Massachusetts Institute of Technology", "Massachusetts", "MA"),
        us("montana", "University of Montana", "Montana", "MT"),
        us("montana-state", "Montana State University", "Montana", "MT"),
        us("naval-academy", "United States Naval Academy", "Maryland", "MD"),
        us("nebraska", "University of Nebraska–Lincoln", "Nebraska", "NE"),
        us("nevada-reno", "University of Nevada, Reno", "Nevada", "NV"),
        us("new-hampshire", "University of New Hampshire", "New Hampshire", "NH"),
        us("new-mexico", "University of New Mexico", "New Mexico", "NM"),
        us("new-mexico-state", "New Mexico State University", "New Mexico", "NM"),
        us("notre-dame", "University of Notre Dame", "Indiana", "IN"),
        us("nyu", "New York University", "New York", "NY"),
        us("north-carolina-state", "North Carolina State University", "North Carolina", "NC"),
        us("north-dakota", "University of North Dakota", "North Dakota", "ND"),
        us("north-dakota-state", "North Dakota State University", "North Dakota", "ND"),
        us("northeastern", "Northeastern University", "Massachusetts", "MA"),
        us("northwestern", "Northwestern University", "Illinois", "IL"),
        us("ohio-state", "Ohio State University", "Ohio", "OH"),
        us("oklahoma", "University of Oklahoma", "Oklahoma", "OK"),
        us("oklahoma-state", "Oklahoma State University", "Oklahoma", "OK"),
        us("oregon", "University of Oregon", "Oregon", "OR"),
        us("oregon-state", "Oregon State University", "Oregon", "OR"),
        us("penn-state", "Pennsylvania State University", "Pennsylvania", "PA"),
        us("princeton", "Princeton University", "New Jersey", "NJ"),
        us("purdue", "Purdue University", "Indiana", "IN"),
        us("rice", "Rice University", "Texas", "TX"),
        us("rutgers", "Rutgers University–New Brunswick", "New Jersey", "NJ"),
        us("south-carolina", "University of South Carolina", "South Carolina", "SC"),
        us("south-dakota", "University of South Dakota", "South Dakota", "SD"),
        us("south-dakota-state", "South Dakota State University", "South Dakota", "SD"),
        us("stanford", "Stanford University", "California", "CA"),
        us("syracuse", "Syracuse University", "New York", "NY"),
        us("temple", "Temple University", "Pennsylvania", "PA"),
        us("tennessee", "University of Tennessee, Knoxville", "Tennessee", "TN"),
        us("texas-am", "Texas A&M University", "Texas", "TX"),
        us("tufts", "Tufts University", "Massachusetts", "MA"),
        us("tulane", "Tulane University", "Louisiana", "LA"),
        us("uc-berkeley", "University of California, Berkeley", "California", "CA"),
        us("uc-davis", "University of California, Davis", "California", "CA"),
        us("uc-irvine", "University of California, Irvine", "California", "CA"),
        us("uc-santa-barbara", "University of California, Santa Barbara", "California", "CA"),
        us("ucsd", "University of California, San Diego", "California", "CA"),
        us("uchicago", "University of Chicago", "Illinois", "IL"),
        us("ucla", "University of California, Los Angeles", "California", "CA"),
        us("uiuc", "University of Illinois Urbana-Champaign", "Illinois", "IL"),
        us("umass-amherst", "University of Massachusetts Amherst", "Massachusetts", "MA"),
        us("umich", "University of Michigan", "Michigan", "MI"),
        us("unc", "University of North Carolina at Chapel Hill", "North Carolina", "NC"),
        us("upenn", "University of Pennsylvania", "Pennsylvania", "PA"),
        us("usc", "University of Southern California", "California", "CA"),
        us("utexas", "University of Texas at Austin", "Texas", "TX"),
        us("utah", "University of Utah", "Utah", "UT"),
        us("vermont", "University of Vermont", "Vermont", "VT"),
        us("vanderbilt", "Vanderbilt University", "Tennessee", "TN"),
        us("virginia", "University of Virginia", "Virginia", "VA"),
        us("virginia-tech", "Virginia Tech", "Virginia", "VA"),
        us("wake-forest", "Wake Forest University", "North Carolina", "NC"),
        us("washington-state", "Washington State University", "Washington", "WA"),
        us("uw", "University of Washington", "Washington", "WA"),
        us("washu", "Washington University in St. Louis", "Missouri", "MO"),
        us("west-virginia", "West Virginia University", "West Virginia", "WV"),
        us("wisconsin", "University of Wisconsin–Madison", "Wisconsin", "WI"),
        us("wyoming", "University of Wyoming", "Wyoming", "WY"),
        us("yale", "Yale University", "Connecticut", "CT"),

        // Canada
        intl("alberta", "University of Alberta", "Alberta", "AB", "Canada"),
        intl("british-columbia", "University of British Columbia", "British Columbia", "BC", "Canada"),
        intl("mcgill", "McGill University", "Quebec", "QC", "Canada"),
        intl("mcmaster", "McMaster University", "Ontario", "ON", "Canada"),
        intl("montreal", "Université de Montréal", "Quebec", "QC", "Canada"),
        intl("ottawa", "University of Ottawa", "Ontario", "ON", "Canada"),
        intl("queens", "Queen's University", "Ontario", "ON", "Canada"),
        intl("simon-fraser", "Simon Fraser University", "British Columbia", "BC", "Canada"),
        intl("utoronto", "University of Toronto", "Ontario", "ON", "Canada"),
        intl("waterloo", "University of Waterloo", "Ontario", "ON", "Canada"),

        // United Kingdom and Ireland
        intl("cambridge", "University of Cambridge", "England", nil, "United Kingdom"),
        intl("edinburgh", "University of Edinburgh", "Scotland", nil, "United Kingdom"),
        intl("imperial", "Imperial College London", "England", nil, "United Kingdom"),
        intl("kings-college-london", "King's College London", "England", nil, "United Kingdom"),
        intl("lse", "London School of Economics and Political Science", "England", nil, "United Kingdom"),
        intl("manchester", "University of Manchester", "England", nil, "United Kingdom"),
        intl("oxford", "University of Oxford", "England", nil, "United Kingdom"),
        intl("st-andrews", "University of St Andrews", "Scotland", nil, "United Kingdom"),
        intl("ucl", "University College London", "England", nil, "United Kingdom"),
        intl("trinity-dublin", "Trinity College Dublin", "Leinster", nil, "Ireland"),

        // Europe
        intl("amsterdam", "University of Amsterdam", nil, nil, "Netherlands"),
        intl("copenhagen", "University of Copenhagen", nil, nil, "Denmark"),
        intl("delft", "Delft University of Technology", nil, nil, "Netherlands"),
        intl("epfl", "EPFL", "Vaud", nil, "Switzerland"),
        intl("eth-zurich", "ETH Zurich", "Zurich", nil, "Switzerland"),
        intl("heidelberg", "Heidelberg University", "Baden-Württemberg", nil, "Germany"),
        intl("ku-leuven", "KU Leuven", "Flemish Brabant", nil, "Belgium"),
        intl("lmu-munich", "LMU Munich", "Bavaria", nil, "Germany"),
        intl("paris-saclay", "Paris-Saclay University", "Île-de-France", nil, "France"),
        intl("sorbonne", "Sorbonne University", "Île-de-France", nil, "France"),
        intl("technical-university-munich", "Technical University of Munich", "Bavaria", nil, "Germany"),

        // Asia and the Middle East
        intl("chinese-university-hong-kong", "Chinese University of Hong Kong", nil, nil, "Hong Kong"),
        intl("hkust", "Hong Kong University of Science and Technology", nil, nil, "Hong Kong"),
        intl("iit-bombay", "Indian Institute of Technology Bombay", "Maharashtra", nil, "India"),
        intl("kaist", "KAIST", "Daejeon", nil, "South Korea"),
        intl("kyoto", "Kyoto University", "Kyoto", nil, "Japan"),
        intl("national-taiwan", "National Taiwan University", "Taipei", nil, "Taiwan"),
        intl("nus", "National University of Singapore", nil, nil, "Singapore"),
        intl("peking", "Peking University", "Beijing", nil, "China"),
        intl("seoul-national", "Seoul National University", "Seoul", nil, "South Korea"),
        intl("technion", "Technion – Israel Institute of Technology", "Haifa", nil, "Israel"),
        intl("tel-aviv", "Tel Aviv University", "Tel Aviv", nil, "Israel"),
        intl("tokyo", "University of Tokyo", "Tokyo", nil, "Japan"),
        intl("tsinghua", "Tsinghua University", "Beijing", nil, "China"),

        // Australia, New Zealand, Africa, and Latin America
        intl("anu", "Australian National University", "Australian Capital Territory", "ACT", "Australia"),
        intl("auckland", "University of Auckland", "Auckland", nil, "New Zealand"),
        intl("cape-town", "University of Cape Town", "Western Cape", nil, "South Africa"),
        intl("melbourne", "University of Melbourne", "Victoria", "VIC", "Australia"),
        intl("monash", "Monash University", "Victoria", "VIC", "Australia"),
        intl("new-south-wales", "University of New South Wales", "New South Wales", "NSW", "Australia"),
        intl("pontifical-catholic-chile", "Pontifical Catholic University of Chile", "Santiago", nil, "Chile"),
        intl("sao-paulo", "University of São Paulo", "São Paulo", "SP", "Brazil"),
        intl("sydney", "University of Sydney", "New South Wales", "NSW", "Australia"),
        intl("unam", "National Autonomous University of Mexico", "Mexico City", nil, "Mexico")
    ] + additionalUSUniversities)
    .sorted {
        if $0.country != $1.country { return $0.country < $1.country }
        if $0.state != $1.state { return ($0.state ?? "") < ($1.state ?? "") }
        return $0.name < $1.name
    }

    static func displayName(for id: String) -> String {
        if id == none.id { return none.name }
        return universities.first(where: { $0.id == id })?.name ?? id
    }

    private static let additionalUSUniversities: [UniversityOption] = [
        .init(id: "us-450933", name: "Columbia Southern University", state: "Alabama", stateCode: "AL", country: "United States"),
        .init(id: "us-102553", name: "University of Alaska Anchorage", state: "Alaska", stateCode: "AK", country: "United States"),
        .init(id: "us-484613", name: "University of Phoenix-Arizona", state: "Arizona", stateCode: "AZ", country: "United States"),
        .init(id: "us-106704", name: "University of Central Arkansas", state: "Arkansas", stateCode: "AR", country: "United States"),
        .init(id: "us-110565", name: "California State University-Fullerton", state: "California", stateCode: "CA", country: "United States"),
        .init(id: "us-126614", name: "University of Colorado Boulder", state: "Colorado", stateCode: "CO", country: "United States"),
        .init(id: "us-130183", name: "Post University", state: "Connecticut", stateCode: "CT", country: "United States"),
        .init(id: "us-131113", name: "Wilmington University", state: "Delaware", stateCode: "DE", country: "United States"),
        .init(id: "us-459994", name: "Strayer University-Global Region", state: "District of Columbia", stateCode: "DC", country: "United States"),
        .init(id: "us-132903", name: "University of Central Florida", state: "Florida", stateCode: "FL", country: "United States"),
        .init(id: "us-486840", name: "Kennesaw State University", state: "Georgia", stateCode: "GA", country: "United States"),
        .init(id: "us-141981", name: "University of Hawaii-West Oahu", state: "Hawaii", stateCode: "HI", country: "United States"),
        .init(id: "us-142276", name: "Idaho State University", state: "Idaho", stateCode: "ID", country: "United States"),
        .init(id: "us-482477", name: "DeVry University-Illinois", state: "Illinois", stateCode: "IL", country: "United States"),
        .init(id: "us-151111", name: "Indiana University-Indianapolis", state: "Indiana", stateCode: "IN", country: "United States"),
        .init(id: "us-154095", name: "University of Northern Iowa", state: "Iowa", stateCode: "IA", country: "United States"),
        .init(id: "us-156125", name: "Wichita State University", state: "Kansas", stateCode: "KS", country: "United States"),
        .init(id: "us-157289", name: "University of Louisville", state: "Kentucky", stateCode: "KY", country: "United States"),
        .init(id: "us-160658", name: "University of Louisiana at Lafayette", state: "Louisiana", stateCode: "LA", country: "United States"),
        .init(id: "us-161572", name: "Unity Environmental University", state: "Maine", stateCode: "ME", country: "United States"),
        .init(id: "us-164076", name: "Towson University", state: "Maryland", stateCode: "MD", country: "United States"),
        .init(id: "us-166638", name: "University of Massachusetts-Boston", state: "Massachusetts", stateCode: "MA", country: "United States"),
        .init(id: "us-170082", name: "Grand Valley State University", state: "Michigan", stateCode: "MI", country: "United States"),
        .init(id: "us-413413", name: "Capella University", state: "Minnesota", stateCode: "MN", country: "United States"),
        .init(id: "us-176372", name: "University of Southern Mississippi", state: "Mississippi", stateCode: "MS", country: "United States"),
        .init(id: "us-179566", name: "Missouri State University-Springfield", state: "Missouri", stateCode: "MO", country: "United States"),
        .init(id: "us-180416", name: "Montana Technological University", state: "Montana", stateCode: "MT", country: "United States"),
        .init(id: "us-181394", name: "University of Nebraska at Omaha", state: "Nebraska", stateCode: "NE", country: "United States"),
        .init(id: "us-182281", name: "University of Nevada-Las Vegas", state: "Nevada", stateCode: "NV", country: "United States"),
        .init(id: "us-183026", name: "Southern New Hampshire University", state: "New Hampshire", stateCode: "NH", country: "United States"),
        .init(id: "us-185590", name: "Montclair State University", state: "New Jersey", stateCode: "NJ", country: "United States"),
        .init(id: "us-187648", name: "Eastern New Mexico University-Main Campus", state: "New Mexico", stateCode: "NM", country: "United States"),
        .init(id: "us-196088", name: "University at Buffalo", state: "New York", stateCode: "NY", country: "United States"),
        .init(id: "us-199139", name: "University of North Carolina at Charlotte", state: "North Carolina", stateCode: "NC", country: "United States"),
        .init(id: "us-200253", name: "Minot State University", state: "North Dakota", stateCode: "ND", country: "United States"),
        .init(id: "us-201885", name: "University of Cincinnati-Main Campus", state: "Ohio", stateCode: "OH", country: "United States"),
        .init(id: "us-206941", name: "University of Central Oklahoma", state: "Oklahoma", stateCode: "OK", country: "United States"),
        .init(id: "us-209807", name: "Portland State University", state: "Oregon", stateCode: "OR", country: "United States"),
        .init(id: "us-215293", name: "University of Pittsburgh-Pittsburgh Campus", state: "Pennsylvania", stateCode: "PA", country: "United States"),
        .init(id: "us-217484", name: "University of Rhode Island", state: "Rhode Island", stateCode: "RI", country: "United States"),
        .init(id: "us-218724", name: "Coastal Carolina University", state: "South Carolina", stateCode: "SC", country: "United States"),
        .init(id: "us-219046", name: "Black Hills State University", state: "South Dakota", stateCode: "SD", country: "United States"),
        .init(id: "us-220978", name: "Middle Tennessee State University", state: "Tennessee", stateCode: "TN", country: "United States"),
        .init(id: "us-228459", name: "Texas State University", state: "Texas", stateCode: "TX", country: "United States"),
        .init(id: "us-433387", name: "Western Governors University", state: "Utah", stateCode: "UT", country: "United States"),
        .init(id: "us-231165", name: "Vermont State University", state: "Vermont", stateCode: "VT", country: "United States"),
        .init(id: "us-232557", name: "Liberty University", state: "Virginia", stateCode: "VA", country: "United States"),
        .init(id: "us-237011", name: "Western Washington University", state: "Washington", stateCode: "WA", country: "United States"),
        .init(id: "us-449339", name: "American Public University System", state: "West Virginia", stateCode: "WV", country: "United States"),
        .init(id: "us-240453", name: "University of Wisconsin-Milwaukee", state: "Wisconsin", stateCode: "WI", country: "United States"),
        .init(id: "us-102368", name: "Troy University", state: "Alabama", stateCode: "AL", country: "United States"),
        .init(id: "us-102632", name: "University of Alaska Southeast", state: "Alaska", stateCode: "AK", country: "United States"),
        .init(id: "us-104717", name: "Grand Canyon University", state: "Arizona", stateCode: "AZ", country: "United States"),
        .init(id: "us-106467", name: "Arkansas Tech University", state: "Arkansas", stateCode: "AR", country: "United States"),
        .init(id: "us-110583", name: "California State University-Long Beach", state: "California", stateCode: "CA", country: "United States"),
        .init(id: "us-126827", name: "Colorado Technical University-Colorado Springs", state: "Colorado", stateCode: "CO", country: "United States"),
        .init(id: "us-128771", name: "Central Connecticut State University", state: "Connecticut", stateCode: "CT", country: "United States"),
        .init(id: "us-130934", name: "Delaware State University", state: "Delaware", stateCode: "DE", country: "United States"),
        .init(id: "us-131159", name: "American University", state: "District of Columbia", stateCode: "DC", country: "United States"),
        .init(id: "us-133951", name: "Florida International University", state: "Florida", stateCode: "FL", country: "United States"),
        .init(id: "us-139940", name: "Georgia State University", state: "Georgia", stateCode: "GA", country: "United States"),
        .init(id: "us-141644", name: "Hawaii Pacific University", state: "Hawaii", stateCode: "HI", country: "United States"),
        .init(id: "us-142461", name: "Northwest Nazarene University", state: "Idaho", stateCode: "ID", country: "United States"),
        .init(id: "us-145600", name: "University of Illinois Chicago", state: "Illinois", stateCode: "IL", country: "United States"),
        .init(id: "us-150136", name: "Ball State University", state: "Indiana", stateCode: "IN", country: "United States"),
        .init(id: "us-153269", name: "Drake University", state: "Iowa", stateCode: "IA", country: "United States"),
        .init(id: "us-155061", name: "Fort Hays State University", state: "Kansas", stateCode: "KS", country: "United States"),
        .init(id: "us-157951", name: "Western Kentucky University", state: "Kentucky", stateCode: "KY", country: "United States"),
        .init(id: "us-160612", name: "Southeastern Louisiana University", state: "Louisiana", stateCode: "LA", country: "United States"),
        .init(id: "us-161554", name: "University of Southern Maine", state: "Maine", stateCode: "ME", country: "United States"),
        .init(id: "us-163453", name: "Morgan State University", state: "Maryland", stateCode: "MD", country: "United States"),
        .init(id: "us-166513", name: "University of Massachusetts-Lowell", state: "Massachusetts", stateCode: "MA", country: "United States"),
        .init(id: "us-172644", name: "Wayne State University", state: "Michigan", stateCode: "MI", country: "United States"),
        .init(id: "us-173920", name: "Minnesota State University-Mankato", state: "Minnesota", stateCode: "MN", country: "United States"),
        .init(id: "us-175856", name: "Jackson State University", state: "Mississippi", stateCode: "MS", country: "United States"),
        .init(id: "us-179159", name: "Saint Louis University", state: "Missouri", stateCode: "MO", country: "United States"),
        .init(id: "us-180258", name: "University of Providence", state: "Montana", stateCode: "MT", country: "United States"),
        .init(id: "us-180814", name: "Bellevue University", state: "Nebraska", stateCode: "NE", country: "United States"),
        .init(id: "us-441900", name: "Nevada State University", state: "Nevada", stateCode: "NV", country: "United States"),
        .init(id: "us-183080", name: "Plymouth State University", state: "New Hampshire", stateCode: "NH", country: "United States"),
        .init(id: "us-184782", name: "Rowan University", state: "New Jersey", stateCode: "NJ", country: "United States"),
        .init(id: "us-188304", name: "Western New Mexico University", state: "New Mexico", stateCode: "NM", country: "United States"),
        .init(id: "us-196097", name: "Stony Brook University", state: "New York", stateCode: "NY", country: "United States"),
        .init(id: "us-198464", name: "East Carolina University", state: "North Carolina", stateCode: "NC", country: "United States"),
        .init(id: "us-200059", name: "Dickinson State University", state: "North Dakota", stateCode: "ND", country: "United States"),
        .init(id: "us-203517", name: "Kent State University at Kent", state: "Ohio", stateCode: "OH", country: "United States"),
        .init(id: "us-207263", name: "Northeastern State University", state: "Oklahoma", stateCode: "OK", country: "United States"),
        .init(id: "us-210429", name: "Western Oregon University", state: "Oregon", stateCode: "OR", country: "United States"),
        .init(id: "us-212054", name: "Drexel University", state: "Pennsylvania", stateCode: "PA", country: "United States"),
        .init(id: "us-217518", name: "Roger Williams University", state: "Rhode Island", stateCode: "RI", country: "United States"),
        .init(id: "us-218964", name: "Winthrop University", state: "South Carolina", stateCode: "SC", country: "United States"),
        .init(id: "us-219000", name: "Augustana University", state: "South Dakota", stateCode: "SD", country: "United States"),
        .init(id: "us-220862", name: "University of Memphis", state: "Tennessee", stateCode: "TN", country: "United States"),
        .init(id: "us-227216", name: "University of North Texas", state: "Texas", stateCode: "TX", country: "United States"),
        .init(id: "us-230737", name: "Utah Valley University", state: "Utah", stateCode: "UT", country: "United States"),
        .init(id: "us-230995", name: "Norwich University", state: "Vermont", stateCode: "VT", country: "United States"),
        .init(id: "us-233921", name: "Virginia Polytechnic Institute and State University", state: "Virginia", stateCode: "VA", country: "United States"),
        .init(id: "us-234827", name: "Central Washington University", state: "Washington", stateCode: "WA", country: "United States"),
        .init(id: "us-237525", name: "Marshall University", state: "West Virginia", stateCode: "WV", country: "United States"),
        .init(id: "us-240329", name: "University of Wisconsin-La Crosse", state: "Wisconsin", stateCode: "WI", country: "United States"),
        .init(id: "us-102094", name: "University of South Alabama", state: "Alabama", stateCode: "AL", country: "United States"),
        .init(id: "us-102669", name: "Alaska Pacific University", state: "Alaska", stateCode: "AK", country: "United States"),
        .init(id: "us-104179", name: "University of Arizona", state: "Arizona", stateCode: "AZ", country: "United States"),
        .init(id: "us-107044", name: "Harding University", state: "Arkansas", stateCode: "AR", country: "United States"),
        .init(id: "us-122409", name: "San Diego State University", state: "California", stateCode: "CA", country: "United States"),
        .init(id: "us-126818", name: "Colorado State University-Fort Collins", state: "Colorado", stateCode: "CO", country: "United States"),
        .init(id: "us-130253", name: "Sacred Heart University", state: "Connecticut", stateCode: "CT", country: "United States"),
        .init(id: "us-450298", name: "Strayer University-Delaware", state: "Delaware", stateCode: "DE", country: "United States"),
        .init(id: "us-131399", name: "University of the District of Columbia", state: "District of Columbia", stateCode: "DC", country: "United States"),
        .init(id: "us-137351", name: "University of South Florida", state: "Florida", stateCode: "FL", country: "United States"),
        .init(id: "us-139931", name: "Georgia Southern University", state: "Georgia", stateCode: "GA", country: "United States"),
        .init(id: "us-141565", name: "University of Hawaii at Hilo", state: "Hawaii", stateCode: "HI", country: "United States"),
        .init(id: "us-145813", name: "Illinois State University", state: "Illinois", stateCode: "IL", country: "United States"),
        .init(id: "us-151324", name: "Indiana State University", state: "Indiana", stateCode: "IN", country: "United States"),
        .init(id: "us-154518", name: "Waldorf University", state: "Iowa", stateCode: "IA", country: "United States"),
        .init(id: "us-155681", name: "Pittsburg State University", state: "Kansas", stateCode: "KS", country: "United States"),
        .init(id: "us-156620", name: "Eastern Kentucky University", state: "Kentucky", stateCode: "KY", country: "United States"),
        .init(id: "us-159647", name: "Louisiana Tech University", state: "Louisiana", stateCode: "LA", country: "United States"),
        .init(id: "us-487524", name: "Husson University", state: "Maine", stateCode: "ME", country: "United States"),
        .init(id: "us-163851", name: "Salisbury University", state: "Maryland", stateCode: "MD", country: "United States"),
        .init(id: "us-165024", name: "Bridgewater State University", state: "Massachusetts", stateCode: "MA", country: "United States"),
        .init(id: "us-172699", name: "Western Michigan University", state: "Michigan", stateCode: "MI", country: "United States"),
        .init(id: "us-175014", name: "Rasmussen University-Minnesota", state: "Minnesota", stateCode: "MN", country: "United States"),
        .init(id: "us-175342", name: "Alcorn State University", state: "Mississippi", stateCode: "MS", country: "United States"),
        .init(id: "us-179557", name: "Southeast Missouri State University", state: "Missouri", stateCode: "MO", country: "United States"),
        .init(id: "us-181002", name: "Creighton University", state: "Nebraska", stateCode: "NE", country: "United States"),
        .init(id: "us-486938", name: "Chamberlain University-Nevada", state: "Nevada", stateCode: "NV", country: "United States"),
        .init(id: "us-183211", name: "Rivier University", state: "New Hampshire", stateCode: "NH", country: "United States"),
        .init(id: "us-185262", name: "Kean University", state: "New Jersey", stateCode: "NJ", country: "United States"),
        .init(id: "us-187897", name: "New Mexico Highlands University", state: "New Mexico", stateCode: "NM", country: "United States"),
        .init(id: "us-196079", name: "Binghamton University", state: "New York", stateCode: "NY", country: "United States"),
        .init(id: "us-197869", name: "Appalachian State University", state: "North Carolina", stateCode: "NC", country: "United States"),
        .init(id: "us-200156", name: "University of Jamestown", state: "North Dakota", stateCode: "ND", country: "United States"),
        .init(id: "us-204857", name: "Ohio University-Main Campus", state: "Ohio", stateCode: "OH", country: "United States"),
        .init(id: "us-207582", name: "Oral Roberts University", state: "Oklahoma", stateCode: "OK", country: "United States"),
        .init(id: "us-209825", name: "University of Portland", state: "Oregon", stateCode: "OR", country: "United States"),
        .init(id: "us-498571", name: "Pennsylvania Western University", state: "Pennsylvania", stateCode: "PA", country: "United States"),
        .init(id: "us-217235", name: "Johnson & Wales University-Providence", state: "Rhode Island", stateCode: "RI", country: "United States"),
        .init(id: "us-218229", name: "Lander University", state: "South Carolina", stateCode: "SC", country: "United States"),
        .init(id: "us-219383", name: "University of Sioux Falls", state: "South Dakota", stateCode: "SD", country: "United States"),
        .init(id: "us-221740", name: "The University of Tennessee-Chattanooga", state: "Tennessee", stateCode: "TN", country: "United States"),
        .init(id: "us-229115", name: "Texas Tech University", state: "Texas", stateCode: "TX", country: "United States"),
        .init(id: "us-230728", name: "Utah State University", state: "Utah", stateCode: "UT", country: "United States"),
        .init(id: "us-231068", name: "SIT Graduate Institute", state: "Vermont", stateCode: "VT", country: "United States"),
        .init(id: "us-232186", name: "George Mason University", state: "Virginia", stateCode: "VA", country: "United States"),
        .init(id: "us-235097", name: "Eastern Washington University", state: "Washington", stateCode: "WA", country: "United States"),
        .init(id: "us-237367", name: "Fairmont State University", state: "West Virginia", stateCode: "WV", country: "United States"),
        .init(id: "us-240189", name: "University of Wisconsin-Whitewater", state: "Wisconsin", stateCode: "WI", country: "United States"),
        .init(id: "us-101480", name: "Jacksonville State University", state: "Alabama", stateCode: "AL", country: "United States"),
        .init(id: "us-105330", name: "Northern Arizona University", state: "Arizona", stateCode: "AZ", country: "United States"),
        .init(id: "us-107983", name: "Southern Arkansas University Main Campus", state: "Arkansas", stateCode: "AR", country: "United States"),
        .init(id: "us-110608", name: "California State University-Northridge", state: "California", stateCode: "CA", country: "United States"),
        .init(id: "us-127565", name: "Metropolitan State University of Denver", state: "Colorado", stateCode: "CO", country: "United States"),
        .init(id: "us-130226", name: "Quinnipiac University", state: "Connecticut", stateCode: "CT", country: "United States"),
        .init(id: "us-131283", name: "The Catholic University of America", state: "District of Columbia", stateCode: "DC", country: "United States"),
        .init(id: "us-134237", name: "Full Sail University", state: "Florida", stateCode: "FL", country: "United States"),
        .init(id: "us-482680", name: "University of North Georgia", state: "Georgia", stateCode: "GA", country: "United States"),
        .init(id: "us-141486", name: "Chaminade University of Honolulu", state: "Hawaii", stateCode: "HI", country: "United States"),
        .init(id: "us-144740", name: "DePaul University", state: "Illinois", stateCode: "IL", country: "United States"),
        .init(id: "us-488679", name: "Indiana Wesleyan University-National & Global", state: "Indiana", stateCode: "IN", country: "United States"),
        .init(id: "us-154235", name: "Saint Ambrose University", state: "Iowa", stateCode: "IA", country: "United States"),
        .init(id: "us-156082", name: "Washburn University", state: "Kansas", stateCode: "KS", country: "United States"),
        .init(id: "us-157447", name: "Northern Kentucky University", state: "Kentucky", stateCode: "KY", country: "United States"),
        .init(id: "us-160038", name: "Northwestern State University of Louisiana", state: "Louisiana", stateCode: "LA", country: "United States"),
        .init(id: "us-161457", name: "University of New England", state: "Maine", stateCode: "ME", country: "United States"),
        .init(id: "us-162007", name: "Bowie State University", state: "Maryland", stateCode: "MD", country: "United States"),
        .init(id: "us-168421", name: "Worcester Polytechnic Institute", state: "Massachusetts", stateCode: "MA", country: "United States"),
        .init(id: "us-171571", name: "Oakland University", state: "Michigan", stateCode: "MI", country: "United States"),
        .init(id: "us-125231", name: "Walden University", state: "Minnesota", stateCode: "MN", country: "United States"),
        .init(id: "us-176479", name: "William Carey University", state: "Mississippi", stateCode: "MS", country: "United States"),
        .init(id: "us-178059", name: "Maryville University of Saint Louis", state: "Missouri", stateCode: "MO", country: "United States"),
        .init(id: "us-181215", name: "University of Nebraska at Kearney", state: "Nebraska", stateCode: "NE", country: "United States"),
        .init(id: "us-445735", name: "Roseman University of Health Sciences", state: "Nevada", stateCode: "NV", country: "United States"),
        .init(id: "us-182795", name: "Franklin Pierce University", state: "New Hampshire", stateCode: "NH", country: "United States"),
        .init(id: "us-185828", name: "New Jersey Institute of Technology", state: "New Jersey", stateCode: "NJ", country: "United States"),
        .init(id: "us-187596", name: "Navajo Technical University", state: "New Mexico", stateCode: "NM", country: "United States"),
        .init(id: "us-195003", name: "Rochester Institute of Technology", state: "New York", stateCode: "NY", country: "United States"),
        .init(id: "us-199218", name: "University of North Carolina Wilmington", state: "North Carolina", stateCode: "NC", country: "United States"),
        .init(id: "us-200572", name: "Valley City State University", state: "North Dakota", stateCode: "ND", country: "United States"),
        .init(id: "us-204024", name: "Miami University-Oxford", state: "Ohio", stateCode: "OH", country: "United States"),
        .init(id: "us-207661", name: "Rogers State University", state: "Oklahoma", stateCode: "OK", country: "United States"),
        .init(id: "us-209506", name: "Oregon Institute of Technology", state: "Oregon", stateCode: "OR", country: "United States"),
        .init(id: "us-216597", name: "Villanova University", state: "Pennsylvania", stateCode: "PA", country: "United States"),
        .init(id: "us-217165", name: "Bryant University", state: "Rhode Island", stateCode: "RI", country: "United States"),
        .init(id: "us-217633", name: "Anderson University", state: "South Carolina", stateCode: "SC", country: "United States"),
        .init(id: "us-219259", name: "Northern State University", state: "South Dakota", stateCode: "SD", country: "United States"),
        .init(id: "us-220075", name: "East Tennessee State University", state: "Tennessee", stateCode: "TN", country: "United States"),
        .init(id: "us-228769", name: "The University of Texas at Arlington", state: "Texas", stateCode: "TX", country: "United States"),
        .init(id: "us-230782", name: "Weber State University", state: "Utah", stateCode: "UT", country: "United States"),
        .init(id: "us-234030", name: "Virginia Commonwealth University", state: "Virginia", stateCode: "VA", country: "United States"),
        .init(id: "us-235316", name: "Gonzaga University", state: "Washington", stateCode: "WA", country: "United States"),
        .init(id: "us-237792", name: "Shepherd University", state: "West Virginia", stateCode: "WV", country: "United States"),
        .init(id: "us-240268", name: "University of Wisconsin-Eau Claire", state: "Wisconsin", stateCode: "WI", country: "United States"),
        .init(id: "us-100654", name: "Alabama A & M University", state: "Alabama", stateCode: "AL", country: "United States"),
        .init(id: "us-445027", name: "American InterContinental University System", state: "Arizona", stateCode: "AZ", country: "United States"),
        .init(id: "us-107512", name: "Ouachita Baptist University", state: "Arkansas", stateCode: "AR", country: "United States"),
        .init(id: "us-110617", name: "California State University-Sacramento", state: "California", stateCode: "CA", country: "United States"),
        .init(id: "us-126562", name: "University of Colorado Denver/Anschutz Medical Campus", state: "Colorado", stateCode: "CO", country: "United States"),
        .init(id: "us-130493", name: "Southern Connecticut State University", state: "Connecticut", stateCode: "CT", country: "United States"),
        .init(id: "us-131876", name: "Trinity Washington University", state: "District of Columbia", stateCode: "DC", country: "United States"),
        .init(id: "us-133669", name: "Florida Atlantic University", state: "Florida", stateCode: "FL", country: "United States"),
        .init(id: "us-141334", name: "University of West Georgia", state: "Georgia", stateCode: "GA", country: "United States"),
        .init(id: "us-141839", name: "University of Hawaii Maui College", state: "Hawaii", stateCode: "HI", country: "United States"),
        .init(id: "us-454227", name: "Chamberlain University-Illinois", state: "Illinois", stateCode: "IL", country: "United States"),
        .init(id: "us-151306", name: "University of Southern Indiana", state: "Indiana", stateCode: "IN", country: "United States"),
        .init(id: "us-154493", name: "Upper Iowa University", state: "Iowa", stateCode: "IA", country: "United States"),
        .init(id: "us-155025", name: "Emporia State University", state: "Kansas", stateCode: "KS", country: "United States"),
        .init(id: "us-157401", name: "Murray State University", state: "Kentucky", stateCode: "KY", country: "United States"),
        .init(id: "us-160621", name: "Southern University and A & M College", state: "Louisiana", stateCode: "LA", country: "United States"),
        .init(id: "us-160995", name: "Beal University", state: "Maine", stateCode: "ME", country: "United States"),
        .init(id: "us-163046", name: "Loyola University Maryland", state: "Maryland", stateCode: "MD", country: "United States"),
        .init(id: "us-167987", name: "University of Massachusetts-Dartmouth", state: "Massachusetts", stateCode: "MA", country: "United States"),
        .init(id: "us-169798", name: "Eastern Michigan University", state: "Michigan", stateCode: "MI", country: "United States"),
        .init(id: "us-174914", name: "University of St Thomas", state: "Minnesota", stateCode: "MN", country: "United States"),
        .init(id: "us-175616", name: "Delta State University", state: "Mississippi", stateCode: "MS", country: "United States"),
        .init(id: "us-176965", name: "University of Central Missouri", state: "Missouri", stateCode: "MO", country: "United States"),
        .init(id: "us-181446", name: "Nebraska Wesleyan University", state: "Nebraska", stateCode: "NE", country: "United States"),
        .init(id: "us-459824", name: "Touro University Nevada", state: "Nevada", stateCode: "NV", country: "United States"),
        .init(id: "us-245865", name: "Antioch University-New England", state: "New Hampshire", stateCode: "NH", country: "United States"),
        .init(id: "us-186876", name: "Stockton University", state: "New Jersey", stateCode: "NJ", country: "United States"),
        .init(id: "us-187967", name: "New Mexico Institute of Mining and Technology", state: "New Mexico", stateCode: "NM", country: "United States"),
        .init(id: "us-196680", name: "Excelsior University", state: "New York", stateCode: "NY", country: "United States"),
        .init(id: "us-199148", name: "University of North Carolina at Greensboro", state: "North Carolina", stateCode: "NC", country: "United States"),
        .init(id: "us-200226", name: "Mayville State University", state: "North Dakota", stateCode: "ND", country: "United States"),
        .init(id: "us-201441", name: "Bowling Green State University-Main Campus", state: "Ohio", stateCode: "OH", country: "United States"),
        .init(id: "us-206914", name: "Cameron University", state: "Oklahoma", stateCode: "OK", country: "United States"),
        .init(id: "us-210146", name: "Southern Oregon University", state: "Oregon", stateCode: "OR", country: "United States"),
        .init(id: "us-213543", name: "Lehigh University", state: "Pennsylvania", stateCode: "PA", country: "United States"),
        .init(id: "us-217536", name: "Salve Regina University", state: "Rhode Island", stateCode: "RI", country: "United States"),
        .init(id: "us-218733", name: "South Carolina State University", state: "South Carolina", stateCode: "SC", country: "United States"),
        .init(id: "us-219204", name: "National American University-Rapid City", state: "South Dakota", stateCode: "SD", country: "United States"),
        .init(id: "us-221847", name: "Tennessee Technological University", state: "Tennessee", stateCode: "TN", country: "United States"),
        .init(id: "us-229027", name: "The University of Texas at San Antonio", state: "Texas", stateCode: "TX", country: "United States"),
        .init(id: "us-230603", name: "Southern Utah University", state: "Utah", stateCode: "UT", country: "United States"),
        .init(id: "us-232423", name: "James Madison University", state: "Virginia", stateCode: "VA", country: "United States"),
        .init(id: "us-236595", name: "Seattle University", state: "Washington", stateCode: "WA", country: "United States"),
        .init(id: "us-237312", name: "University of Charleston", state: "West Virginia", stateCode: "WV", country: "United States"),
        .init(id: "us-240365", name: "University of Wisconsin-Oshkosh", state: "Wisconsin", stateCode: "WI", country: "United States"),
        .init(id: "us-101879", name: "University of North Alabama", state: "Alabama", stateCode: "AL", country: "United States"),
        .init(id: "us-104586", name: "Embry-Riddle Aeronautical University-Prescott", state: "Arizona", stateCode: "AZ", country: "United States"),
        .init(id: "us-107071", name: "Henderson State University", state: "Arkansas", stateCode: "AR", country: "United States"),
        .init(id: "us-122755", name: "San Jose State University", state: "California", stateCode: "CA", country: "United States"),
        .init(id: "us-126580", name: "University of Colorado Colorado Springs", state: "Colorado", stateCode: "CO", country: "United States"),
        .init(id: "us-129242", name: "Fairfield University", state: "Connecticut", stateCode: "CT", country: "United States"),
        .init(id: "us-131450", name: "Gallaudet University", state: "District of Columbia", stateCode: "DC", country: "United States"),
        .init(id: "us-135081", name: "Keiser University-Ft Lauderdale", state: "Florida", stateCode: "FL", country: "United States"),
        .init(id: "us-141264", name: "Valdosta State University", state: "Georgia", stateCode: "GA", country: "United States"),
        .init(id: "us-457484", name: "Pacific Rim Christian University", state: "Hawaii", stateCode: "HI", country: "United States"),
        .init(id: "us-146719", name: "Loyola University Chicago", state: "Illinois", stateCode: "IL", country: "United States"),
        .init(id: "us-150163", name: "Butler University", state: "Indiana", stateCode: "IN", country: "United States"),
        .init(id: "us-153250", name: "Dordt University", state: "Iowa", stateCode: "IA", country: "United States"),
        .init(id: "us-154688", name: "Baker University", state: "Kansas", stateCode: "KS", country: "United States"),
        .init(id: "us-156541", name: "University of the Cumberlands", state: "Kentucky", stateCode: "KY", country: "United States"),
        .init(id: "us-159993", name: "University of Louisiana at Monroe", state: "Louisiana", stateCode: "LA", country: "United States"),
        .init(id: "us-462044", name: "Institute for Doctoral Studies in the Visual Arts", state: "Maine", stateCode: "ME", country: "United States"),
        .init(id: "us-164173", name: "Stevenson University", state: "Maryland", stateCode: "MD", country: "United States"),
        .init(id: "us-168005", name: "Suffolk University", state: "Massachusetts", stateCode: "MA", country: "United States"),
        .init(id: "us-169248", name: "Central Michigan University", state: "Michigan", stateCode: "MI", country: "United States"),
        .init(id: "us-174783", name: "Saint Cloud State University", state: "Minnesota", stateCode: "MN", country: "United States"),
        .init(id: "us-176035", name: "Mississippi University for Women", state: "Mississippi", stateCode: "MS", country: "United States"),
        .init(id: "us-178411", name: "Missouri University of Science and Technology", state: "Missouri", stateCode: "MO", country: "United States"),
        .init(id: "us-180984", name: "Concordia University-Nebraska", state: "Nebraska", stateCode: "NE", country: "United States"),
        .init(id: "us-482547", name: "DeVry University-Nevada", state: "Nevada", stateCode: "NV", country: "United States"),
        .init(id: "us-440004", name: "Upper Valley Educators Institute", state: "New Hampshire", stateCode: "NH", country: "United States"),
        .init(id: "us-187046", name: "Thomas Edison State University", state: "New Jersey", stateCode: "NJ", country: "United States"),
        .init(id: "us-188182", name: "University of the Southwest", state: "New Mexico", stateCode: "NM", country: "United States"),
        .init(id: "us-196060", name: "University at Albany", state: "New York", stateCode: "NY", country: "United States"),
        .init(id: "us-199102", name: "North Carolina A & T State University", state: "North Carolina", stateCode: "NC", country: "United States"),
        .init(id: "us-200013", name: "Rasmussen University-North Dakota", state: "North Dakota", stateCode: "ND", country: "United States"),
        .init(id: "us-206084", name: "University of Toledo", state: "Ohio", stateCode: "OH", country: "United States"),
        .init(id: "us-207971", name: "University of Tulsa", state: "Oklahoma", stateCode: "OK", country: "United States"),
        .init(id: "us-208822", name: "George Fox University", state: "Oregon", stateCode: "OR", country: "United States"),
        .init(id: "us-212106", name: "Duquesne University", state: "Pennsylvania", stateCode: "PA", country: "United States"),
        .init(id: "us-460349", name: "Johnson & Wales University-Online", state: "Rhode Island", stateCode: "RI", country: "United States"),
        .init(id: "us-217688", name: "Charleston Southern University", state: "South Carolina", stateCode: "SC", country: "United States"),
        .init(id: "us-219198", name: "Mount Marty University", state: "South Dakota", stateCode: "SD", country: "United States"),
        .init(id: "us-219602", name: "Austin Peay State University", state: "Tennessee", stateCode: "TN", country: "United States"),
        .init(id: "us-227368", name: "The University of Texas Rio Grande Valley", state: "Texas", stateCode: "TX", country: "United States"),
        .init(id: "us-230171", name: "Utah Tech University", state: "Utah", stateCode: "UT", country: "United States"),
        .init(id: "us-232982", name: "Old Dominion University", state: "Virginia", stateCode: "VA", country: "United States"),
        .init(id: "us-236230", name: "Pacific Lutheran University", state: "Washington", stateCode: "WA", country: "United States"),
        .init(id: "us-237932", name: "West Liberty University", state: "West Virginia", stateCode: "WV", country: "United States"),
        .init(id: "us-239105", name: "Marquette University", state: "Wisconsin", stateCode: "WI", country: "United States"),
        .init(id: "us-102049", name: "Samford University", state: "Alabama", stateCode: "AL", country: "United States"),
        .init(id: "us-105534", name: "Pima Medical Institute-Tucson", state: "Arizona", stateCode: "AZ", country: "United States"),
        .init(id: "us-107600", name: "Philander Smith University", state: "Arkansas", stateCode: "AR", country: "United States"),
        .init(id: "us-110529", name: "California State Polytechnic University-Pomona", state: "California", stateCode: "CA", country: "United States"),
        .init(id: "us-127556", name: "Colorado Mesa University", state: "Colorado", stateCode: "CO", country: "United States"),
        .init(id: "us-129941", name: "University of New Haven", state: "Connecticut", stateCode: "CT", country: "United States"),
        .init(id: "us-131803", name: "Strayer University-District of Columbia", state: "District of Columbia", stateCode: "DC", country: "United States"),
        .init(id: "us-136172", name: "University of North Florida", state: "Florida", stateCode: "FL", country: "United States"),
        .init(id: "us-482158", name: "Middle Georgia State University", state: "Georgia", stateCode: "GA", country: "United States"),
        .init(id: "us-420042", name: "University of Phoenix-Hawaii", state: "Hawaii", stateCode: "HI", country: "United States"),
        .init(id: "us-147703", name: "Northern Illinois University", state: "Illinois", stateCode: "IL", country: "United States"),
        .init(id: "us-151342", name: "Indiana University-South Bend", state: "Indiana", stateCode: "IN", country: "United States"),
        .init(id: "us-153278", name: "University of Dubuque", state: "Iowa", stateCode: "IA", country: "United States"),
        .init(id: "us-155089", name: "Friends University", state: "Kansas", stateCode: "KS", country: "United States"),
        .init(id: "us-157386", name: "Morehead State University", state: "Kentucky", stateCode: "KY", country: "United States"),
        .init(id: "us-159717", name: "McNeese State University", state: "Louisiana", stateCode: "LA", country: "United States"),
        .init(id: "us-162584", name: "Frostburg State University", state: "Maryland", stateCode: "MD", country: "United States"),
    ]

    private static func us(_ id: String, _ name: String, _ state: String, _ stateCode: String) -> UniversityOption {
        UniversityOption(id: id, name: name, state: state, stateCode: stateCode, country: "United States")
    }

    private static func intl(
        _ id: String,
        _ name: String,
        _ state: String?,
        _ stateCode: String?,
        _ country: String
    ) -> UniversityOption {
        UniversityOption(id: id, name: name, state: state, stateCode: stateCode, country: country)
    }
}
